install(FILES
	engines/cengine/src/avdl_achievements.c
	engines/cengine/src/avdl_achievements_steam.cpp
	engines/cengine/src/avdl_assetManager.c
	engines/cengine/src/avdl_data.c
	engines/cengine/src/avdl_localisation.c
	engines/cengine/src/avdl_multiplayer.c
	engines/cengine/src/avdl_multiplayer_steam.cpp
	engines/cengine/src/avdl_particle_system.c
	engines/cengine/src/avdl_steam_cpp.cpp
	engines/cengine/src/avdl_particle_system.c
	engines/cengine/src/avdl_shaders.c
	engines/cengine/src/avdl_steam.c
	engines/cengine/src/dd_dynamic_array.c
	engines/cengine/src/dd_filetomesh.c
	engines/cengine/src/dd_fov.c
	engines/cengine/src/dd_game.c
	engines/cengine/src/dd_gamejolt.c
	engines/cengine/src/dd_image.c
	engines/cengine/src/dd_json.c
	engines/cengine/src/dd_log.c
	engines/cengine/src/dd_log_cpp.cpp
	engines/cengine/src/dd_math.c
	engines/cengine/src/dd_matrix.c
	engines/cengine/src/dd_mesh.c
	engines/cengine/src/dd_meshColour.c
	engines/cengine/src/dd_meshTexture.c
	engines/cengine/src/dd_mouse.c
	engines/cengine/src/dd_music.c
	engines/cengine/src/dd_sound.c
	engines/cengine/src/dd_string3d.c
	engines/cengine/src/dd_vec3.c
	engines/cengine/src/dd_vec4.c
	engines/cengine/src/dd_world.c
	engines/cengine/src/main.c
	engines/cengine/src/main_cpp.cpp
	engines/cengine/src/avdl_input.c
	engines/cengine/src/whereami.c
	engines/cengine/src/avdl_physics.c
	engines/cengine/src/avdl_collider.c
	engines/cengine/src/avdl_collider_aabb.c
	engines/cengine/src/avdl_collider_sphere.c
	engines/cengine/src/avdl_rigidbody.c
	engines/cengine/src/avdl_graphics_opengl.c
	engines/cengine/src/avdl_graphics_direct3d11.cpp
	engines/cengine/src/avdl_engine.c
	engines/cengine/src/avdl_engine_cpp.cpp
	DESTINATION
	share/avdl/cengine
)
install(FILES
	engines/cengine/include/avdl_achievements.h
	engines/cengine/include/avdl_assetManager.h
	engines/cengine/include/avdl_cengine.h
	engines/cengine/include/avdl_data.h
	engines/cengine/include/avdl_localisation.h
	engines/cengine/include/avdl_multiplayer.h
	engines/cengine/include/avdl_particle_system.h
	engines/cengine/include/avdl_shaders.h
	engines/cengine/include/avdl_steam.h
	engines/cengine/include/dd_async_call.h
	engines/cengine/include/dd_dynamic_array.h
	engines/cengine/include/dd_filetomesh.h
	engines/cengine/include/dd_fov.h
	engines/cengine/include/dd_game.h
	engines/cengine/include/dd_gamejolt.h
	engines/cengine/include/dd_image.h
	engines/cengine/include/dd_json.h
	engines/cengine/include/dd_log.h
	engines/cengine/include/dd_math.h
	engines/cengine/include/dd_matrix.h
	engines/cengine/include/dd_meshColour.h
	engines/cengine/include/dd_mesh.h
	engines/cengine/include/dd_meshTexture.h
	engines/cengine/include/dd_mouse.h
	engines/cengine/include/dd_music.h
	engines/cengine/include/dd_sound.h
	engines/cengine/include/dd_string3d.h
	engines/cengine/include/dd_vec2.h
	engines/cengine/include/dd_vec3.h
	engines/cengine/include/dd_vec4.h
	engines/cengine/include/dd_world.h
	engines/cengine/include/avdl_input.h
	engines/cengine/include/whereami.h
	engines/cengine/include/avdl_physics.h
	engines/cengine/include/avdl_collider.h
	engines/cengine/include/avdl_collider_aabb.h
	engines/cengine/include/avdl_collider_sphere.h
	engines/cengine/include/avdl_rigidbody.h
	engines/cengine/include/avdl_graphics.h
	engines/cengine/include/avdl_engine.h
	DESTINATION
	include
)
