# avdl is written in C
language: c

# make builds on `bionic` and `xenial` ubuntu images
# on both `amd64` and `arm64` architectures
jobs:
  include:
    - name: bionic build
      os: linux
      dist: bionic
      arch: amd64
    - name: bionic build
      os: linux
      dist: bionic
      arch: arm64
    - name: xenial build
      os: linux
      dist: xenial
      arch: amd64
    - name: xenial build
      os: linux
      dist: xenial
      arch: arm64

# install dependencies
addons:
  apt:
    packages:
      - git
      - make
      - freeglut3-dev
      - libglew-dev
      - libsdl2-dev
      - libsdl2-mixer-dev

# compile project
script: make
