# avdl is written in C
language: c

# make builds on `bionic` and `xenial` ubuntu images
jobs:
  include:
    - name: bionic build
      os: linux
      dist: bionic
    - name: xenial build
      os: linux
      dist: xenial

# build for both amd64 and arm64
arch:
  - amd64
  - arm64

# install dependencies
addons:
  apt:
    packages:
      - git
      - make
      - freeglut3-dev
      - libglew-dev
      - libsdl2-dev
      - libsdl2-mixer-dev

# compile project
script: make
