name: avdl
base: core18
version: '0.9.8'
summary: Abstract video-game development language compiler
description: |
  A high level video game programming language.
  Games made with it are meant to be described in an abstract way
  and be compiled for a variety of platforms.

grade: stable
confinement: classic

apps:
  avdl:
    command: bin/avdl

parts:
  avdl:
    source: https://github.com/tomtsagk/avdl/archive/refs/tags/v0.9.8.tar.gz
    plugin: make
    make-parameters: [ 'prefix=' ]
    build-packages:
        - libglew-dev
        - libsdl2-dev
        - libsdl2-mixer-dev
        - libpng-dev
        - libvorbis-dev
        - libogg0
    stage-packages:
        - libglew-dev
        - libsdl2-dev
        - libsdl2-mixer-dev
        - libpng-dev
        - libvorbis-dev
        - libogg0
