name: C/C++ CI

# only execute on new version tags (ex. v0.0.0)
on:
  push:
    branches:
      github-test-stable

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        configs: [Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
