name: Build Dependencies

on:
  push:
    branches:
      - feature/build_dependencies

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: libpng - linux
      run: |
        git clone git://git.code.sf.net/p/libpng/code libpng
        cd libpng
        ./configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make -j6
        make -j6 install
        cd ..
    - name: ogg - linux
      run: |
        git clone https://gitlab.xiph.org/xiph/ogg.git ogg
        cd ogg
        ./autogen.sh
        ./configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make -j6
        make -j6 install
        cd ..
    - name: vorbis - linux
      run: |
        git clone https://gitlab.xiph.org/xiph/vorbis.git vorbis
        cd vorbis
        ./autogen.sh
        ./configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make
        make install
        cd ..
    - name: opus - linux
      run: |
        git clone https://gitlab.xiph.org/xiph/opus.git opus
        cd opus
        ./autogen.sh
        ./configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make
        make install
        cd ..
    - name: opusfile - linux
      run: |
        export PKG_CONFIG_PATH=${HOME}/AVDL_DEPENDENCIES
        git clone https://gitlab.xiph.org/xiph/opusfile.git opusfile
        cd opusfile
        ./autogen.sh
        ./configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make -j6
        make -j6 install
        cd ..
    - name: sdl - linux
      run: |
        export C_INCLUDE_PATH=${HOME}/AVDL_DEPENDENCIES/include
        export LIBRARY_PATH=${HOME}/AVDL_DEPENDENCIES/lib:${HOME}/AVDL_DEPENDENCIES/lib64
        git clone https://github.com/libsdl-org/SDL SDL
        cd SDL
        git checkout release-2.0.20
        mkdir build
        cd build
        ../configure --prefix=${HOME}/AVDL_DEPENDENCIES
        make -j6
        make -j6 install
        cd ../..
    - name: sdl_mixer - linux
      run: |
        git clone https://github.com/libsdl-org/SDL_mixer SDL_mixer
        cd SDL_mixer
        git checkout release-2.0.4
        mkdir build
        cd build
        ../configure --prefix=${HOME}/AVDL_DEPENDENCIES --enable-music-ogg-vorbis
        make -j6
        make -j6 install
        cd ../..
    - name: glew - linux
      run: |
        git clone https://github.com/nigels-com/glew glew
        cd glew
        git checkout glew-2.2.0
        cd auto
        make
        cd ..
        make GLEW_DEST=${HOME}/AVDL_DEPENDENCIES
        make GLEW_DEST=${HOME}/AVDL_DEPENDENCIES install
        cd ..
