name: Unit Tests

# for now only run on `develop` and `master`
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

# run dependencies, build project, test project
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Dependencies
      run: |
         sudo apt update && sudo apt install -y valgrind lcov gcc libglew-dev libsdl2-dev libsdl2-mixer-dev libpng-dev libfreetype-dev

    - uses: actions/checkout@v1

    - name: Build
      run: |
        make -j4 prefix=/usr CC=gcc

    - name: Tests
      run: |
       make -j4 CC=gcc test-advance

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
