name: Unit Tests

# run only on active branched, and on pull requests for `development`
on:
  push:
    branches:
      - github
      - development
      - stable
  pull_request:
    branches:
      - development

# run dependencies, build project, test project
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Dependencies
      run: |
         sudo apt update && sudo apt install -y valgrind lcov gcc libglew-dev libsdl2-dev libsdl2-mixer-dev

    - uses: actions/checkout@v1

    - name: Build
      run: |
        make -j4 prefix=/usr CC=gcc

    - name: Tests
      run: |
       make -j4 CC=gcc test-advance

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
